package com.example.soulscript.ui.theme

import androidx.compose.ui.graphics.Color

// Light Theme Colors
val LightPrimary = Color(0xFF006A6A)
val LightOnPrimary = Color(0xFFFFFFFF)
val LightPrimaryContainer = Color(0xFF70F7F6)
val LightOnPrimaryContainer = Color(0xFF002020)
val LightSecondary = Color(0xFF4A6363)
val LightOnSecondary = Color(0xFFFFFFFF)
val LightSecondaryContainer = Color(0xFFCCE8E7)
val LightOnSecondaryContainer = Color(0xFF051F1F)
val LightTertiary = Color(0xFF4B607C)
val LightOnTertiary = Color(0xFFFFFFFF)
val LightTertiaryContainer = Color(0xFFD3E4FF)
val LightOnTertiaryContainer = Color(0xFF041C35)
val LightError = Color(0xFFBA1A1A)
val LightErrorContainer = Color(0xFFFFDAD6)
val LightOnError = Color(0xFFFFFFFF)
val LightOnErrorContainer = Color(0xFF410002)
val LightBackground = Color(0xFFFAFDFD)
val LightOnBackground = Color(0xFF191C1C)
val LightSurface = Color(0xFFF7FAFA)
val LightOnSurface = Color(0xFF191C1C)
val LightSurfaceVariant = Color(0xFFDAE5E4)
val LightOnSurfaceVariant = Color(0xFF3F4948)
val LightOutline = Color(0xFF6F7979)

// Dark Theme Colors
val DarkPrimary = Color(0xFF4DDADA)
val DarkOnPrimary = Color(0xFF003737)
val DarkPrimaryContainer = Color(0xFF005050)
val DarkOnPrimaryContainer = Color(0xFF70F7F6)
val DarkSecondary = Color(0xFFB0CCCB)
val DarkOnSecondary = Color(0xFF1B3534)
val DarkSecondaryContainer = Color(0xFF324B4B)
val DarkOnSecondaryContainer = Color(0xFFCCE8E7)
val DarkTertiary = Color(0xFFB3C8E8)
val DarkOnTertiary = Color(0xFF1B314B)
val DarkTertiaryContainer = Color(0xFF334863)
val DarkOnTertiaryContainer = Color(0xFFD3E4FF)
val DarkError = Color(0xFFFF1F00)
val DarkErrorContainer = Color(0xFF93000A)
val DarkOnError = Color(0xFFFCFCFC)
val DarkOnErrorContainer = Color(0xFFFFDAD6)
val DarkBackground = Color(0xFF191C1C)
val DarkOnBackground = Color(0xFFE0E3E3)
val DarkSurface = Color(0xFF222828)
val DarkOnSurface = Color(0xFFE0E3E3)
val DarkSurfaceVariant = Color(0xFF3F4948)
val DarkOnSurfaceVariant = Color(0xFFBFC9C8)
val DarkOutline = Color(0xFF899392)